version: '3.8'

services:
  docker:
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-storage:/var/lib/docker
    networks:
      - jenkins

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2375:2375"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - docker
    networks:
      - jenkins

volumes:
  jenkins-data:
  dind-storage:

networks:
  jenkins:
