services:
  jenkins:
    image: jenkins-with-docker-cli
    container_name: jenkins
    user: root
    privileged: true  # docker daemon kullanımı için gerekli
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # docker socket'i container'a bağla
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock

volumes:
  jenkins_home:
