# Use official Playwright image with browsers installed
#FROM mcr.microsoft.com/playwright:v1.46.0-jammy

# Use official Node LTS base image
#FROM node:lts

FROM jenkins/jenkins:lts

USER root

# install Java (if you need the plugin’s JDK too)
RUN apt-get update \
 && apt-get install -y openjdk-17-jdk wget unzip \
 && rm -rf /var/lib/apt/lists/*

# install Allure CLI 2.21.0
RUN wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.zip -O /tmp/allure.zip \
 && unzip /tmp/allure.zip -d /opt/ \
 && ln -s /opt/allure-2.21.0/bin/allure /usr/local/bin/allure \
 && rm /tmp/allure.zip

# Docker CLI kur
RUN apt-get update \
    && apt-get install -y docker.io \
    && rm -rf /var/lib/apt/lists/*

# Install AWS CLI
RUN apt-get update && \
    apt-get install -y awscli && \
    rm -rf /var/lib/apt/lists/*

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

USER jenkins

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

# Set working directory inside container
#WORKDIR /app

# Copy package.json and package-lock.json first (for caching)
#COPY package*.json ./

# Install dependencies
#RUN npm ci
# Install Playwright browsers (chromium, firefox, webkit) and all dependencies
#RUN npx playwright install 

# Copy all source files
#COPY . .

# Default command to run tests
#CMD ["npx", "playwright", "test"]
