name: Smoke Tests on PR
on:
  schedule:
    - cron: '0 2 * * *' # Everyday at 2 AM Scheduled Run
  push:
    branches: [  "**"  ]
  pull_request:
    branches: [  "**"  ]

permissions:
  contents: write  # Permission to push to gh-pages

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # Cache Node modules
    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: |
         node_modules
         ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    # Cache Playwright browsers
    - id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}-${{ hashFiles('playwright.config.ts') }}
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Allure CLI
      run: npm install -g allure-commandline
    - name: Run Playwright tests
      run: npx playwright test --grep "@smoke"
      if: ${{ always() }}
    - name: Run Cucumber tests
      run: npx cucumber-js
      if: ${{ always() }}
    - name: Generate Allure report
      run: npx allure generate allure-results --clean -o allure-report
      if: ${{ always() }}
    - name: Debug allure-report folder
      run: ls -la allure-report
      if: ${{ always() }}

    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: playwright-report
        path: playwright-report/
    - name: Upload Allure report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 7
    - name: Install rclone
      if: ${{ always() }}
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Deploy Playwright Report to GitHub Pages
      if: ${{ always() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report
        publish_branch: gh-pages